apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: pyland
data:
  # Override for production
  DEBUG: "False"
  ALLOWED_HOSTS: "pylandschool.com,www.pylandschool.com,api.pylandschool.com"
