apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: pyland
data:
  # Django settings
  DJANGO_SETTINGS_MODULE: "pyland.settings"
  ALLOWED_HOSTS: "*"  # Override in overlays
  DEBUG: "False"

  # Database
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pyland_db"

  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"

  # Application
  TIME_ZONE: "UTC"
  LANGUAGE_CODE: "ru-ru"
