apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: pyland
data:
  # Override for staging
  DEBUG: "False"
  ALLOWED_HOSTS: "staging.pylandschool.com,*.staging.pylandschool.com"
